"""add relation_types table

Revision ID: 9bbc72f7c470
Revises: 
Create Date: 2026-06-02 21:56:00.628729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bbc72f7c470'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_relations', schema=None) as batch_op:
        batch_op.alter_column('source_note_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('target_note_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    op.create_table('relation_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_types_name'), 'relation_types', ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_relations', schema=None) as batch_op:
        batch_op.alter_column('target_note_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('source_note_id',
               existing_type=sa.INTEGER(),
               nullable=False)
               
    op.drop_index(op.f('ix_relation_types_name'), table_name='relation_types')
    op.drop_table('relation_types')

    # ### end Alembic commands ###
